shorter commands, names

diff --git a/bin/copy_server_files b/bin/copy_server_files
--- a/bin/copy_server_files
+++ b/bin/copy_server_files
@@ -7,8 +7,8 @@ set -e
 if [ -z "$OPENVPN" ]; then
     export OPENVPN="$PWD"
 fi
-if ! source "$OPENVPN/ovpn_env.sh"; then
-    echo "Could not source $OPENVPN/ovpn_env.sh."
+if ! source "$OPENVPN/env.sh"; then
+    echo "Could not source $OPENVPN/env.sh."
     exit 1
 fi
 
@@ -23,7 +23,7 @@ rm -rf "$TARGET/pki/private" "$TARGET/pki/issued"
 
 FILES=(
     "openvpn.conf"
-    "ovpn_env.sh"
+    "env.sh"
     "pki/private/${OVPN_CN}.key"
     "pki/issued/${OVPN_CN}.crt"
     "pki/dh.pem"
diff --git a/bin/getclient b/bin/getclient
--- a/bin/getclient
+++ b/bin/getclient
@@ -13,8 +13,8 @@ set -e
 if [ -z "$OPENVPN" ]; then
     export OPENVPN="$PWD"
 fi
-if ! source "$OPENVPN/ovpn_env.sh"; then
-    echo "Could not source $OPENVPN/ovpn_env.sh."
+if ! source "$OPENVPN/env.sh"; then
+    echo "Could not source $OPENVPN/env.sh."
     exit 1
 fi
 if [ -z "$EASYRSA_PKI" ]; then
diff --git a/bin/getclient_all b/bin/getclient_all
--- a/bin/getclient_all
+++ b/bin/getclient_all
@@ -5,8 +5,8 @@
 if [ -z "$OPENVPN" ]; then
     export OPENVPN="$PWD"
 fi
-if ! source "$OPENVPN/ovpn_env.sh"; then
-    echo "Could not source $OPENVPN/ovpn_env.sh."
+if ! source "$OPENVPN/env.sh"; then
+    echo "Could not source $OPENVPN/env.sh."
     exit 1
 fi
 if [ -z "$EASYRSA_PKI" ]; then
@@ -18,8 +18,8 @@ for name in issued/*.crt; do
     name=${name%.crt}
     name=${name#issued/}
     if [ "$name" != "$OVPN_CN" ]; then
-        ovpn_getclient "$name" separated
-        ovpn_getclient "$name" combined-save
+        getclient "$name" separated
+        getclient "$name" combined-save
     fi
 done
 popd
diff --git a/bin/otp_user b/bin/otp_user
--- a/bin/otp_user
+++ b/bin/otp_user
@@ -4,8 +4,8 @@
 # Generate OpenVPN users via google authenticator
 #
 
-if ! source "$OPENVPN/ovpn_env.sh"; then
-    echo "Could not source $OPENVPN/ovpn_env.sh."
+if ! source "$OPENVPN/env.sh"; then
+    echo "Could not source $OPENVPN/env.sh."
     exit 1
 fi
 
@@ -15,7 +15,7 @@ if [ "x$OVPN_OTP_AUTH" != "x1" ]; then
 fi
 
 if [ -z $1 ]; then
-    echo "Usage: ovpn_otp_user USERNAME"
+    echo "Usage: otp_user USERNAME"
     exit 1
 fi
 
