var, trans

diff --git a/bin/send b/bin/send
--- a/bin/send
+++ b/bin/send
@@ -1,28 +1,27 @@
 #!/bin/bash
+cz=clients.tar.xz
 echo -e "1. Email  \n2. Telegram \n3. Don't send"
 read s
 if [[ "${s}" =~ ^([0-9]) ]]; then
    if [[ $s -lt 4 ]]; then
-      echo "Архивация"
-       tar -cJf clietns.tar.xz "$OPENVPN"/clients/$CLIENTNAME || :
-       echo "Подготовка к отправке"
+      echo "Archiving..."
+       tar -cJf $cz "$OPENVPN"/clients/$CLIENTNAME || :
        fi
          if [ "$s" == "1" ]; then
-         echo "Отправка на почту..."
-         echo -e "to: $EmailUN\nsubject: Clients OVPN\n"| (cat - && uuencode clietns.tar.xz clietns.tar.xz ) | ssmtp $EmailUN && rm clients.tar.xz
+         echo "Sending to email"
+         echo -e "to: $EmailUN\nsubject: Clients OVPN\n"| (cat - && uuencode $cz $cz ) | ssmtp $EmailUN && rm $cz
          fi
          if [ "$s" == "2" ]; then
-         echo "Отправка в Telegram"
+         echo "Sending to Telegram"
          curdir=$PWD
          echo sending $curdir/$1
-         curl -F chat_id=$chat_id -F document=@$curdir/clietns.tar.xz https://api.telegram.org/bot$botToken/sendDocument && \
-         rm clients.tar.xz
+         curl -F chat_id=$chat_id -F document=@$curdir/$cz https://api.telegram.org/bot$botToken/sendDocument && rm $cz
          fi
          if [ "$s" == "3" ]; then
-         echo "Эхит"
+         echo "Exit."
          fi
          else
-      echo "error: ..."
+      echo "error: Wrong number"
    fi        
 else
 echo "error: Not a number" >&2; exit 1
